### ISSUE TITLE
Remove calls to chrome plugin as it no-longer works

### ISSUE THREAD

**Issue by jdanish** [theRAPTLab/meme#133]
Chrome no-longer supports the plugin we made to automatically do screen captures. Our sense is that due to covid, most kids know how to do screen captures, so we don't need the plugin. Can you remove the code calls that ping the plugin and produce a console error since we will no-longer need the plugin? Ideally this could go into the final app build but no real rush.

**Comment by benloh** [comment]
@jdanish I'm not seeing this error message.  Isn't the plug in just an extension that needs to be removed from the browser?

**Comment by jdanish** [comment]
I don't have the plugin anymore but see this. 

<img width="1249" alt="Screenshot 2024-01-16 at 3 14 45 PM" src="https://github.com/theRAPTLab/meme/assets/5529898/f2d569c5-18be-4140-9670-1249062f1f67">

**Comment by benloh** [comment]
Implemented with 603190d248c9f79b4a355ab56dcd3baa39f2f6d3
