### ISSUE TITLE
Simplify Evidence Link Editing

### ISSUE THREAD

**Issue by benloh** [theRAPTLab/meme#141]
Joshua writes:
Right now when you look at a piece of evidence, there is a big notes field (rarely used) and then the evidence links. We are thinking: a) remove notes, b) re-lable the links as "ideas" (to replace the note-taking idea) and c) make them appear in 2 steps (with the same basic content just re-organized) so that initially kids just type an idea and possibly attach a screen shot. Then, IF / WHEN they link the idea to their model, the box expands to include the fields for rating and explanation to reflect that link. We think this will make it more intuitive and help scaffold the sequence of noting an idea, then linking it and explaining the link. Does that sound doable / quick?

See https://docs.google.com/presentation/d/1a3lLhJ8DZjiMAKZVRjk_xFCzopxu1xcZGWyBDjg8Iag/edit#slide=id.p

Needed before January

**Comment by jdanish** [comment]
One additional minor change - if the evidence link is there, then displaying it as in the current version works. If it is not, leave the space blank instead of having a red button that says not linked.

**Comment by benloh** [comment]
* [x] a) remove notes
* [x] b) re-lable the links as "ideas" (to replace the note-taking idea) and 
* [x] c) make them appear in 2 steps (with the same basic content just re-organized) so that initially kids just type an idea and possibly attach a screen shot.

**Comment by benloh** [comment]
@jdanish Since the first field is already labeled "IDEA" I wasn't sure if you wanted the top "EVIDENCE LINK" to be relabeled as "IDEAS"?

![screenshot_1381](https://github.com/theRAPTLab/meme/assets/1403057/1f1e634c-2643-4de9-9b76-643604ad8560)

**Comment by jdanish** [comment]
Let's leave it for now thanks.
